language: python
sudo: false

python:
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - TASK=lint
    - TASK=check-format
    - TASK=check-py27
    - TASK=check-py35
    - TASK=check-pypy

script:
  - make $TASK

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
