language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - env: TASK=lint
      python: "3.5"

script:
  - make $TASK

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
